Update automerge.yml

diff --git a/.github/workflows/automerge.yml b/.github/workflows/automerge.yml
--- a/.github/workflows/automerge.yml
+++ b/.github/workflows/automerge.yml
@@ -65,19 +65,22 @@ jobs:
       - name: Check out code
         uses: actions/checkout@v2
 
-      - name: Merge feature-develop into main
+      - name: Attempt to merge merge-test into merge-master
+        id: merge_result
         run: |
-          # git config user.name "GitHub Actions"
-          # git config user.email "<actions@github.com>"
-          git fetch origin
-          git checkout main
-          if git merge feature-develop --no-ff --no-edit --allow-unrelated-histories; then
+          set -e
+          git merge feature-develop --no-ff --no-edit --allow-unrelated-histories || echo "Merge failed"
+
+      - name: Check merge result
+        run: |
+          if [ "${{ steps.merge_result.outcome }}" == "success" ]; then
             git push origin main
+          else
             # Notify the author of the merge conflict and provide instructions
             commit_author=$(git --no-pager show -s --format='%an' HEAD)
-            echo "$commit_author"
             commit_author_email=$(git --no-pager show -s --format='%ae' HEAD)
-            echo "Merge conflict detected in the branch 'feature-develop'. Please resolve the conflict and rebase if necessary. Instructions: [Link to conflict resolution guide]. /cc @$commit_author" >> conflict_message.txt
+            echo "$commit_author"
+            echo "Merge conflict detected in the branch 'merge-test'. Please resolve the conflict and rebase if necessary. Instructions: [Link to conflict resolution guide]. /cc @$commit_author" >> conflict_message.txt
             echo "CONFLICT_DETECTED=true" >> env.properties
             echo "CONFLICT_MESSAGE=$(cat conflict_message.txt)" >> env.properties
             echo "CONFLICT_AUTHOR=$commit_author" >> env.properties
