Update automerge.yml

diff --git a/.github/workflows/automerge.yml b/.github/workflows/automerge.yml
--- a/.github/workflows/automerge.yml
+++ b/.github/workflows/automerge.yml
@@ -27,32 +27,33 @@ jobs:
       - name: Check out code
         uses: actions/checkout@v2
 
-      # - name: Attempt to merge merge-test into merge-master
-      #   id: merge_result
-      #   run: |
-      #     set -e
-      #     git merge feature-develop --no-ff --no-edit --allow-unrelated-histories || echo "Merge failed"
+      - name: Attempt to merge merge-test into merge-master
+        id: merge_result
+        run: |
+          set -e
+          git merge main --no-ff --no-edit --allow-unrelated-histories || echo "Merge failed"
 
       # - name: Setup Git User
       #   run: |
       #     git config user.name "GitHub Action"
       #     git config user.email "<EMAIL>"
           
-      - name: Merge the PR
-        id: merge-status
-        #continue-on-error: true
-        run: |
-            git checkout main
-            git fetch origin
-            git checkout feature-develop
-            git pull
-            git merge --allow-unrelated-histories origin/main
-            git push origin feature-develop
+      # - name: Merge the PR
+      #   id: merge-status
+      #   #continue-on-error: true
+      #   run: |
+      #       git checkout main
+      #       git fetch origin
+      #       git checkout feature-develop
+      #       git pull
+      #       git merge --allow-unrelated-histories origin/main
+      #       git push origin feature-develop
           
       - name: Check merge result
         id: step1
-        if: steps.merge-status.outcome == 'failure'
+        #if: steps.merge-status.outcome == 'failure'
         run: |
+          if [ "${{ steps.merge_result.outcome }}" == "success" ]; then
           #   git push origin main
           # else
             # Notify the author of the merge conflict and provide instructions
@@ -64,7 +65,7 @@ jobs:
             echo "conflict_detected=true" >> $GITHUB_OUTPUT
             echo "conflict_messages=$(cat conflict_message.txt)" >> $GITHUB_OUTPUT
             echo "conflict_author=$commit_author" >> $GITHUB_OUTPUT
-          #fi
+          fi
                 
       # - name: Set environment variables
       #   id: init
