Update automerge.yml

diff --git a/.github/workflows/automerge.yml b/.github/workflows/automerge.yml
--- a/.github/workflows/automerge.yml
+++ b/.github/workflows/automerge.yml
@@ -1,10 +1,9 @@
-
-name: Merge feature-develop into main and Notify Authors
+name: Merge main into feature-develop and Notify Authors
 
 on: 
   push:
     branches:
-      - feature-develop
+      - main
   issues:
   pull_request:
     
@@ -27,16 +26,32 @@ jobs:
       - name: Check out code
         uses: actions/checkout@v2
 
-      - name: Attempt to merge merge-test into merge-master
-        id: merge_result
-        run: |
-          set -e
-          git merge feature-develop --no-ff --no-edit --allow-unrelated-histories || echo "Merge failed"
+      # - name: Attempt to merge merge-test into merge-master
+      #   id: merge_result
+      #   run: |
+      #     set -e
+      #     git merge feature-develop --no-ff --no-edit --allow-unrelated-histories || echo "Merge failed"
 
+      - name: Setup Git User
+        run: |
+          git config user.name "GitHub Action"
+          git config user.email "<EMAIL>"
+          
+      - name: Merge the PR
+        id: merge-status
+        shell: bash
+        run: |
+            git checkout main
+            git fetch origin
+            git checkout feature-develop
+            git pull
+            git merge --allow-unrelated-histories origin/main
+            git push origin feature-develop
+          
       - name: Check merge result
         id: step1
         run: |
-          if [ "${{ steps.merge_result.outcome }}" == "success" ]; then
+          if [ "${{ steps.merge-status.outcome }}" == "success" ]; then
           #   git push origin main
           # else
             # Notify the author of the merge conflict and provide instructions
